name: cml-chatbot

on: [issue_comment]

jobs:
  chatbot:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml:latest

    if: | 
      (github.event.issue.pull_request != null) && (
        contains(github.event.comment.body, '/cml-cloud-runner' ||
        contains(github.event.comment.body, '/cml-publish'
      ))   

    steps:
      - name: Fetch PR
        id: chatops
        uses: actions/github-script@v1
        with:
          github-token: ${{ secrets.repo_token }}
          script: |
            github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.issue.number
            }).then( (pr) => {
              console.log(`::set-output name=SHA::${pr.data.head.sha}`
              console.log(`::set-output name=COMMAND::${github.event.comment.body}`
            )})
            
      - name: test
        env:
          repo_token: ${{ secrets.repo_token }}
        run: |
          ${steps.chatops.outputs.COMMAND} > report.md
          cml-send-comment report.md --commit-sha ${{ steps.chatops.outputs.SHA }}
