name: cml-chatbot

on: [issue_comment]

jobs:
  chatbot:
    #runs-on: [ubuntu-latest]
    runs-on: [self-hosted, test,unregister]
    #container: docker://dvcorg/cml:latest

    steps:
      - name: Fetch PR
        id: chatops
        uses: actions/github-script@v1
        env:
            COMMAND: ${{github.event.comment.body}}
        with:
          github-token: ${{ secrets.repo_token }}
          script: |
            github.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.issue.number
            }).then( (pr) => {
                // Get latest SHA of current branch
                var SHA = pr.data.head.sha
                console.log(`::set-output name=SHA::${SHA}`)
                console.log(`::set-output name=COMMAND::${process.env.COMMAND}`)
            })
            
      - name: test
        env:
          repo_token: ${{ secrets.repo_token }}
        run: |
          ${{steps.chatops.outputs.COMMAND}} > report.md
          cat report.md
          printenv
          #cml-send-comment report.md
