name: train-my-model

on: [push]

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    container: docker://davidgortega/cml:runner2

    steps:
      - name: deploy
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "Deploying..."

          MACHINE=aws1
          docker-machine create \
              --driver amazonec2 \
              --amazonec2-instance-type t2.micro \
              --amazonec2-region us-east-1 \
              --amazonec2-zone f \
              --amazonec2-vpc-id vpc-06bc773d85a0a04f7 \
              --amazonec2-ssh-user ubuntu \
              $MACHINE

          eval "$(docker-machine env --shell sh $MACHINE)"

          docker-machine ssh $MACHINE "sudo mkdir -p /docker_machine && sudo chmod 777 /docker_machine"
          docker-machine scp -r -q ~/.docker/machine/ $MACHINE:/docker_machine
          docker-machine ssh $MACHINE "ls /docker_machine/machine"

          docker run -d \
            -v /docker_machine/machine:/root/.docker/machine \
            -e DOCKER_MACHINE=${MACHINE} \
            -e RUNNER_LABELS=gpu \
            -e RUNNER_TOKEN=AADFJ53GTUQE7SXR7VIYTP26Z4SVG \
            -e RUNNER_REPO=https://github.com/DavidGOrtega/3_tensorboard \
            davidgortega/cml:runner2

          sleep 30

          echo "Deployed"

  ml:
    needs: deploy
    runs-on: [self-hosted,gpu]
    # container: docker://davidgortega/cml:runner

    steps:
      - uses: actions/checkout@v2

      - name: dvc_cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          echo "Training..."
          echo "hello"
          echo "Trained!"
          