name: train-my-model

on: [push]

jobs:
  # deploy:
  #   runs-on: [ubuntu-latest]
  #   container: docker://davidgortega/cml:runner

  #   steps:
  #     - name: deploy
  #       env:
  #         repo_token: ${{ secrets.GITHUB_TOKEN }} 
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       run: |
  #         echo "Deploying..."

  #         docker-machine create \
  #             --driver amazonec2 \
  #             --amazonec2-instance-type t2.micro \
  #             --amazonec2-region us-east-1 \
  #             --amazonec2-zone f \
  #             --amazonec2-vpc-id vpc-06bc773d85a0a04f7 \
  #             --amazonec2-ssh-user ubuntu \
  #             aws1

  #         eval "$(docker-machine env --shell sh aws1)"
  #         docker run \
  #           -e RUNNER_TOKEN=AADFJ5ZHJHZDXTSG5XG3UVS6ZUYHK \
  #           -e RUNNER_REPO=https://github.com/DavidGOrtega/3_tensorboard \
  #           davidgortega/cml:runner
  #         echo y | docker-machine rm aws1

  #         echo "Deployed"

  job2:
    runs-on: [self-hosted]
    # container: docker://davidgortega/cml:runner

    steps:
      - uses: actions/checkout@v2

      - name: dvc_cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          echo "Training..."
          echo "Trained!"
          