name: train-my-model

on: [push, pull_request]

jobs:    
  deploy-tf:
    runs-on: [ubuntu-latest]
    #runs-on: [ubuntu-18.04]
    #container: docker://dvcorg/cml:latest

    steps:
      - uses: actions/checkout@v2

      - uses: iterative/setup-cml@v1

      - name: deploy
        shell: bash
        env:
          repo_token: ${{ secrets.REPO_TOKEN }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        run: |
          test-cml-cloud-runner \
          --labels=tf \
          --type=t2.micro \
          --region us-west-1 \
          --idle-timeout=120
          --attached

  train:
    needs: deploy-tf
    runs-on: [self-hosted,tf]
    #runs-on: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2

      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          echo "Training..."
          
          #sleep 600 
          echo 'Hi from cml! END message' >> report.md
          # nvidia-smi >> report.md

          cml-send-comment report.md
          echo "Trained!"
